<?php

namespace AppBundle\Repository;

/**
 * ProceedingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProceedingRepository extends \Doctrine\ORM\EntityRepository
{
}
