<?php

namespace AppBundle\Repository;

/**
 * SplitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SplitRepository extends \Doctrine\ORM\EntityRepository
{
}
